### ISSUE TITLE
WebConsole project : the port used by webUI is not secured

### ISSUE THREAD

**Issue by nathalie21005** [abousselmi/docker-free5gc#4]
Hi @abousselmi ,

I am facing a problem with webconsole project which is not secure and make my system vulnerable.
I know how to fix the code but I need your help to tell me how to override the webUI container by adding my changes.
I took a fork from free5gc/webconsole project but where can I in the yaml file should I do the changes to read from my github instead of free5gc github?

Your help is much appreciated.

Regards,
Nathalie Wehbe

**Comment by abousselmi** [comment]
Hi @nathalie21005 

This project is not maintained anymore. Can you please raise your issue in https://github.com/free5gc/free5gc-compose/ ? I'd be glad to provide an answer there.

I'm closing this issue.

Regards,
